### ISSUE TITLE
mold: error: undefined symbol: _Unwind_Resume

### ISSUE THREAD

**Issue by theoparis** [jiripospisil/archlinux-aur-llvm-libunwind#1]
This error appears when trying to compile software with LLVM and lld or mold.

The fix seems to be to replace arch's libunwind  with llvm libunwind. It's quite a hack but I had to remove /usr/lib/libunwind.so.1, and move /usr/libunwind.so.1.0 to /usr/libunwind.so to fix this issue. 

See https://github.com/jiripospisil/archlinux-aur-llvm-libunwind/blob/master/PKGBUILD#L36

**Comment by theoparis** [comment]
I updated this pkgbuild to llvm 17.0.4 and fixed this issue here https://github.com/theoparis/archlinux-aur-llvm-libunwind
I haven't dealt with integrity checks though.

**Comment by jiripospisil** [comment]
I'm not exactly sure what's the right way to fix this. `/usr/lib/libunwind.so` is already owned by the official `extra/libunwind` package and provides a different library (https://github.com/llvm/llvm-project/tree/main/libunwind vs https://github.com/libunwind/libunwind). Are all of those packages which depend on `extra/libunwind` compatible with the LLVM's version? I don't know, doubt it. Maybe you just need to adjust your build script to pick up the LLVM's version?

Also, Arch's llvm+clang is lagging behind and is currently at 16.0.6. Not sure what's blocking it exactly but it lagged for several months even for 16.

**Comment by theoparis** [comment]
Yeah that is probably a better solution. I wasn't sure how to get cmake to pick up the right libunwind though. I think the reason it is lagging behind was because zig hasn't released a version with LLVM 17 yet...
